--Inserted Data to OLD Table
--DONE


DECLARE @query NVARCHAR(MAX)
DECLARE @SQL_SCRIPT NVARCHAR(MAX)
DECLARE @DB1_Name NVARCHAR(50)
DECLARE @DB2_Name NVARCHAR(50)


SET @DB1_Name = '[LEADRS_CORE_DEV_DUI]';
SET @DB2_Name = '[LEADRS_TX_STAGING]';


SET @query = '
SET IDENTITY_INSERT {DB1Name}.dre.TBL_OPT_DRE_ROLES ON

insert into {DB1Name}.dre.TBL_OPT_DRE_ROLES
(	[DRERoleId],
	[Role],
	[Active]
)
select [DRE_ROLE_ID],
	[DRE_ROLE],
	[ACTIVE]
from {DB2Name}.dbo.TBL_OPT_DRE_ROLE
WHERE [DRE_ROLE_ID] NOT IN (
    SELECT [DRERoleId]
    FROM {DB1Name}.dre.TBL_OPT_DRE_ROLES
)

SET IDENTITY_INSERT {DB1Name}.dre.TBL_OPT_DRE_ROLES OFF';



SET @SQL_SCRIPT = REPLACE(@query, '{DB1Name}', @DB1_Name)
SET @SQL_SCRIPT = REPLACE(@SQL_SCRIPT, '{DB2Name}', @DB2_Name)

EXECUTE (@SQL_SCRIPT)

