--DONE


DECLARE @query NVARCHAR(MAX)
DECLARE @SQL_SCRIPT NVARCHAR(MAX)
DECLARE @DB1_Name NVARCHAR(50)
DECLARE @DB2_Name NVARCHAR(50)


SET @DB1_Name = '[LEADRS_CORE_DEV_DUI]';
SET @DB2_Name = '[LEADRS_TX_STAGING]';


SET @query = '
SET IDENTITY_INSERT {DB1Name}.dre.DRE_CASES_OTHER_OFFICER ON

INSERT INTO {DB1Name}.dre.DRE_CASES_OTHER_OFFICER
(	[OtherOfficerId],
	[DreCaseId],
	[DreRoleId],
	[OfficerAgency],
	[OfficerDeptId],
	[DreNumber],
	[OfficerId],
	[OfficerName],
	[PBT],
	[RollingLogNumber],
	[OfficerUserId]
)
SELECT [DRE_CASE_OTHER_OFFICER_ID],
	TBL_DRE_CASE_OTHER_OFFICER.[DRE_CASE_ID],
	TBL_DRE_CASE_OTHER_OFFICER.[DRE_ROLE_ID],
	[OFF_AGENCY],
	[OFF_DEPT_ID],
	[OFF_DRE],
	[OFF_ID],
	[OFF_NAME],
	[PBT],
	TBL_DRE_CASE_OTHER_OFFICER.[ROLLING_LOG_NUMBER],
	[USER_ID]
FROM {DB2Name}.dbo.TBL_DRE_CASE_OTHER_OFFICER
	,{DB2Name}.dbo.TBL_DRE_CASE
WHERE TBL_DRE_CASE_OTHER_OFFICER.DRE_CASE_ID = TBL_DRE_CASE.DRE_CASE_ID
	AND
	[DRE_CASE_OTHER_OFFICER_ID] NOT IN (
    SELECT [OtherOfficerId]
    FROM {DB1Name}.dre.DRE_CASES_OTHER_OFFICER
	WHERE DRE_CASES_OTHER_OFFICER.DreCaseId = TBL_DRE_CASE.DRE_CASE_ID
)
ORDER BY DRE_CASE_OTHER_OFFICER_ID

SET IDENTITY_INSERT {DB1Name}.dre.DRE_CASES_OTHER_OFFICER OFF';



SET @SQL_SCRIPT = REPLACE(@query, '{DB1Name}', @DB1_Name)
SET @SQL_SCRIPT = REPLACE(@SQL_SCRIPT, '{DB2Name}', @DB2_Name)

EXECUTE (@SQL_SCRIPT)


