--DONE

DECLARE @query NVARCHAR(MAX)
DECLARE @SQL_SCRIPT NVARCHAR(MAX)
DECLARE @DB1_Name NVARCHAR(50)
DECLARE @DB2_Name NVARCHAR(50)


SET @DB1_Name = '[LEADRS_CORE_DEV_DUI]';
SET @DB2_Name = '[LEADRS_TX_STAGING]';


SET @query = '
SET IDENTITY_INSERT {DB1Name}.dre.DRE_CASE_INTOX_SALIVA_SCREEN ON
ALTER TABLE {DB1Name}.dre.DRE_CASE_INTOX_SALIVA_SCREEN
NOCHECK CONSTRAINT ALL

INSERT INTO {DB1Name}.dre.DRE_CASE_INTOX_SALIVA_SCREEN
(	[DreSalivaToxResultId],
	DreCaseIntoxilyzerReportId,
	ToxScreenResultId,
	Comment
)
SELECT DRE_SALIVA_TOX_RESULT_ID,
	DRE_INTOX_ID,
	TOX_SCREEN_RESULT_ID,
	COMMENT
from {DB2Name}.dbo.TBL_DRE_CASE_INTOX_SALIVA_SCREEN
ALTER TABLE {DB1Name}.dre.DRE_CASE_INTOX_SALIVA_SCREEN
CHECK CONSTRAINT ALL

SET IDENTITY_INSERT {DB1Name}.dre.DRE_CASE_INTOX_SALIVA_SCREEN OFF';



SET @SQL_SCRIPT = REPLACE(@query, '{DB1Name}', @DB1_Name)
SET @SQL_SCRIPT = REPLACE(@SQL_SCRIPT, '{DB2Name}', @DB2_Name)


EXECUTE (@SQL_SCRIPT)


