--DONE


DECLARE @query NVARCHAR(MAX)
DECLARE @SQL_SCRIPT NVARCHAR(MAX)
DECLARE @DB1_Name NVARCHAR(50)
DECLARE @DB2_Name NVARCHAR(50)


SET @DB1_Name = '[LEADRS_CORE_DEV_DUI]';
SET @DB2_Name = '[LEADRS_TX_STAGING]';


SET @query = '
insert into {DB1Name}.dre.DRE_CASE_AO_INTERVIEWS
(	DreCaseId,
	DateTimeOfArrest,
	OfficerInterview,
	SubjectAttitudCompareDesc,
	SubjectAttitudeDesc,
	SubjectComplainedInjury,
	SubjectComplainedInjuryDesc,
	SubjectDrivingVehicleDesc,
	SubjectFoundBallonPlastic,
	SubjectFoundBallonPlasticDesc,
	SubjectFoundDrugResidue,
	SubjectFoundDrugResidueDesc,
	SubjectFoundInjectionMaterial,
	SubjectFoundInjectionMaterialDesc,
	SubjectFoundMaterial,
	SubjectFoundMaterialDesc,
	SubjectFoundPrescriptionBottles,
	SubjectFoundPrescriptionBottlesDesc,
	SubjectInhalingSubstance,
	SubjectInhalingSubstanceDesc,
	SubjectMentionPrescription,
	SubjectMentionPrescriptionDesc,
	SubjectOpertingVehicle,
	SubjectOpertingVehicleDesc,
	SubjectRespondingStopDesc,
	SubjectRespondToOfficer,
	SubjectSeenSmokeDrink,
	SubjectSeenSmokeDrinkDesc,
	SubjectSpeechAppearSlurred,
	SubjectSpeechAppearSlurredDesc,
	SubjectTryConcealOrThrowMaterial,
	SubjectTryConcealOrThrowMaterialDesc,
	SubjectUsedSteetNameDrug,
	SubjectUsedSteetNameDrugDesc,
	SubjectVehicleCrashed,
	SubjectVehicleCrashedDesc
)
select DRE_CASE_ID,
	ARREST_DATE,
	AO_INTERVIEW,
	SUBJECT_ATTITUDE_COMPARE_DESC,
	SUBJECT_ATTITUDE_DESC,
	SUBJECT_COMPLAINED_ILLNESS_OR_INJURY,
	SUBJECT_COMPLAINED_ILLNESS_OR_INJURY_DESC,
	SUBJECT_DRIVING_VEHICLE_DESC,
	SUBJECT_FOUND_BALLOON_PLASTIC_BAGS,
	SUBJECT_FOUND_BALLOON_PLASTIC_BAGS_DESC,
	SUBJECT_FOUND_DRUG_RESIDUE_PARAPHERNALIA,
	SUBJECT_FOUND_DRUG_RESIDUE_PARAPHERNALIA_DESC,
	SUBJECT_FOUND_SMOKING_PARAPHERNALIA_OR_INJECTION_MATERIAL,
	SUBJECT_FOUND_SMOKING_PARAPHERNALIA_OR_INJECTION_MATERIAL_DESC,
	SUBJECT_FOUND_MATERIAL,
	SUBJECT_FOUND_MATERIAL_DESC,
	SUBJECT_FOUND_PRESCRIPTION_BOTTLES,
	SUBJECT_FOUND_PRESCRIPTION_BOTTLES_DESC,
	SUBJECT_INHALING_SUBSTANCE,
	SUBJECT_INHALING_SUBSTANCE_DESC,
	SUBJECT_MENTION_PRESCRIPTION,
	SUBJECT_MENTION_PRESCRIPTION_DESC,
	SUBJECT_OPERATING_VEHICLE,
	SUBJECT_OPERATING_VEHICLE_DESC,
	SUBJECT_RESPONDING_TO_STOP_DESC,
	SUBJECT_RESPOND_TO_OFFICER_DESC,
	SUBJECT_SEEN_SMOKING_DRINKING,
	SUBJECT_SEEN_SMOKING_DRINKING_DESC,
	SUBJECT_SPEECH_APPEAR_SLURRED,
	SUBJECT_SPEECH_APPEAR_SLURRED_DESC,
	SUBJECT_TRY_CONCEAL_OR_THROW_MATERIAL,
	SUBJECT_TRY_CONCEAL_OR_THROW_MATERIAL_DESC,
	SUBJECT_USED_STEET_NAME_WITH_DRUGS,
	SUBJECT_USED_STEET_NAME_WITH_DRUGS_DESC,
	SUBJECT_VEHICLE_CRASHED,
	SUBJECT_VEHICLE_CRASHED_DESC
from {DB2Name}.dbo.TBL_DRE_CASE
WHERE [DRE_CASE_ID] NOT IN (
    SELECT [DreCaseId]
    FROM {DB1Name}.dre.DRE_CASE_AO_INTERVIEWS
	WHERE DRE_CASE_AO_INTERVIEWS.DreCaseId = TBL_DRE_CASE.DRE_CASE_ID
)

';


SET @SQL_SCRIPT = REPLACE(@query, '{DB1Name}', @DB1_Name)
SET @SQL_SCRIPT = REPLACE(@SQL_SCRIPT, '{DB2Name}', @DB2_Name)

EXECUTE (@SQL_SCRIPT)




