--DONE 


DECLARE @query NVARCHAR(MAX)
DECLARE @SQL_SCRIPT NVARCHAR(MAX)
DECLARE @DB1_Name NVARCHAR(50)
DECLARE @DB2_Name NVARCHAR(50)


SET @DB1_Name = '[LEADRS_CORE_DEV_DUI]';
SET @DB2_Name = '[LEADRS_TX_STAGING]';


SET @query = '
SET IDENTITY_INSERT {DB1Name}.dre.DRE_CASE_IMAGES ON

INSERT INTO {DB1Name}.dre.DRE_CASE_IMAGES
(	[DreCaseImageId],
	[DreCaseId]
)
SELECT [DRE_CASE_IMAGES_ID],
    TBL_DRE_CASE_IMAGES.[DRE_CASE_ID]

FROM {DB2Name}.dbo.TBL_DRE_CASE_IMAGES
	,{DB2Name}.dbo.TBL_DRE_CASE

WHERE TBL_DRE_CASE_IMAGES.DRE_CASE_ID = TBL_DRE_CASE.DRE_CASE_ID
	AND
	[DRE_CASE_IMAGES_ID] NOT IN (
    SELECT [DreCaseImageId]
    FROM {DB1Name}.dre.DRE_CASE_IMAGES
	WHERE DRE_CASE_IMAGES.DreCaseId = TBL_DRE_CASE.DRE_CASE_ID
)

SET IDENTITY_INSERT {DB1Name}.dre.DRE_CASE_IMAGES OFF';


SET @SQL_SCRIPT = REPLACE(@query, '{DB1Name}', @DB1_Name)
SET @SQL_SCRIPT = REPLACE(@SQL_SCRIPT, '{DB2Name}', @DB2_Name)

EXECUTE (@SQL_SCRIPT)


