--DONE


DECLARE @query NVARCHAR(MAX)
DECLARE @SQL_SCRIPT NVARCHAR(MAX)
DECLARE @DB1_Name NVARCHAR(50)
DECLARE @DB2_Name NVARCHAR(50)


SET @DB1_Name = '[LEADRS_CORE_DEV_DUI]';
SET @DB2_Name = '[LEADRS_TX_STAGING]';


SET @query = '
SET IDENTITY_INSERT {DB1Name}.dre.DRE_CASES_OBS ON

insert into {DB1Name}.dre.DRE_CASES_OBS
(	[DreCaseObservationsId],
	AttitudeAnxious,
    AttitudeApologetic,
    AttitudeCareFree,
    AttitudeCocky,
    AttitudeCombative,
    AttitudeConfused,
    AttitudeCooperative,
    AttitudeDazed,
    AttitudeDisoriented,
    AttitudeExcited,
    AttitudeIndifferent,
    AttitudeNonCommunicative,
    AttitudeOther,
    AttitudeParanoid,
    AttitudePassive,
    AttitudeRelaxed,
    AttitudeRestless,
    AttitudeTalkative,
    AttitudeUninhibited,
    BalanceDepressedReflexes,
    BalanceFallingDown,
    BalanceMoonWalking,
    BalanceNeededSupport,
    BalanceNormal,
    BalancePoor,
    BalanceSlow,
    BalanceSluggish,
    BalanceSwaying,
    BalanceUncoordinated,
    BalanceUnsteady,
    BlindnessComment,
    BlindnessLeft,
    BlindnessNone,
    BlindnessRight,
    BreathAlcohol,
    BreathBad,
    BreathChemical,
    BreathMarijuana,
    BreathNormal,
    BreathOther,
    Contacts,
    ContactsHard,
    ContactsSoft,
    CoordinationOther,
    EyesBloodShot,
    EyesNormal,
    EyesRed,
    EyesWatery,
    FaceBlankStare,
    FaceBruxism,
    FaceDazedAppearance,
    FaceDryMouth,
    FaceFacialItching,
    FaceFlushed,
    FaceInjuries,
    FaceNormal,
    FaceOnTheNod,
    FaceOpenSores,
    FaceOther,
    FacePale,
    FaceResidueOfSubstance,
    FaceScars,
    FaceSweatyPerspiring,
    Glasses,
    LensesNone,
    SpeechIncoherent,
    SpeechIncompleteVerbalResposes,
    SpeechLow,
    SpeechNormal,
    SpeechOther,
    SpeechRapidFast,
    SpeechRaspy,
    SpeechSlow,
    SpeechSlowMumbled,
    SpeechSlurred,
    SpeechThickTongued,
    TrackingEqual,
    TrackingUnequal,
    TrackingUnequalDesc,
    WalkingFalling,
    WalkingHeavyFooted,
    WalkingNormal,
    WalkingStaggering,
    WalkingSwaying,
    DreCaseId,
    EyelidsDroopy,
    EyelidsNormal
)
select [DRE_CASE_OBS_ID],
	[Attitude_Anxious],
    [ATTITUDE_APOLOGETIC],
    [Attitude_CareFree],
    [ATTITUDE_COCKY],
    [ATTITUDE_COMBATIVE],
    [Attitude_Confused],
    [ATTITUDE_COOPERATIVE],
    [Attitude_Dazed],
    [Attitude_Disoriented],
    [Attitude_Excited],
    [ATTITUDE_INDIFFERENT],
    [Attitude_Non_Communicative],
    [ATTITUDE_OTHER],
    [Attitude_Paranoid],
    [Attitude_Passive],
    [Attitude_Relaxed],
    [Attitude_Restless],
    [Attitude_Talkative],
    [Attitude_Uninhibited],
    [BALANCE_DepressedReflexes],
    [BALANCE_FALLING_DOWN],
    [BALANCE_MoonWalking],
    [BALANCE_NEEDED_SUPPORT],
    [BALANCE_NORMAL],
    [BALANCE_Poor],
    [BALANCE_Slow],
    [BALANCE_Sluggish],
    [BALANCE_SWAYING],
    [BALANCE_Uncoordinated],
    [BALANCE_UNSTEADY],
    [BLINDNESS_COMMENT],
    [BLINDNESS_LEFT],
    [BLINDNESS_NONE],
    [BLINDNESS_RIGHT],
    [BREATH_ALCOHOL],
    [BREATH_BAD],
    [BREATH_CHEMICAL],
    [BREATH_MARIJUANA],
    [BREATH_NORMAL],
    [BREATH_OTHER],
    [CONTACTS],
    [CONTACTS_HARD],
    [CONTACTS_SOFT],
    [COORDINATION_OTHER],
    [EYES_BLOODSHOT],
    [EYES_NORMAL],
    [EYES_RED],
    [EYES_WATERY],
    [FACE_BLANK_STARE],
    [FACE_BRUXISM],
    [FACE_DAZED_APPEARANCE],
    [FACE_DRY_MOUTH],
    [FACE_FACIAL_ITCHING],
    [FACE_FLUSHED],
    [FACE_INJURIES],
    [FACE_NORMAL],
    [FACE_ON_THE_NOD],
    [FACE_OPEN_SORES],
    [FACE_OTHER],
    [FACE_PALE],
    [FACE_RESIDUE_OF_SUBSTANCE],
    [FACE_SCARS],
    [FACE_SWEATY_PERSPIRING],
    [GLASSES],
    [LENSES_NONE],
    [SPEECH_INCOHERENT],
    [SPEECH_INCOMPLETE_VERBAL_RESPONSES],
    [SPEECH_LOW],
    [SPEECH_NORMAL],
    [SPEECH_OTHER],
    [SPEECH_RAPID_FAST],
    [SPEECH_RASPY],
    [SPEECH_SLOW],
    [SPEECH_SLOW_MUMBLED],
    [SPEECH_SLURRED],
    [SPEECH_THICK_TONGUED],
    [TRACKING_EQUAL],
    [TRACKING_UNEQUAL],
    [TRACKING_UNEQUAL_DESC],
    [WALKING_FALLING],
    [WALKING_HEAVY_FOOTED],
    [WALKING_NORMAL],
    [WALKING_STAGGERING],
    [WALKING_SWAYING],
	TBL_DRE_CASE_OBS.[DRE_CASE_ID],
	[EYELIDS_DROOPY],
	[EYELIDS_NORMAL]
from {DB2Name}.dbo.TBL_DRE_CASE_OBS,
	{DB2Name}.dbo.TBL_DRE_CASE
WHERE TBL_DRE_CASE_OBS.DRE_CASE_ID = TBL_DRE_CASE.DRE_CASE_ID
	AND
	[DRE_CASE_OBS_ID] NOT IN (
    SELECT [DreCaseObservationsId]
    FROM {DB1Name}.dre.DRE_CASES_OBS
	WHERE DRE_CASES_OBS.DreCaseId = TBL_DRE_CASE.DRE_CASE_ID
)
	
SET IDENTITY_INSERT {DB1Name}.dre.DRE_CASES_OBS OFF';



SET @SQL_SCRIPT = REPLACE(@query, '{DB1Name}', @DB1_Name)
SET @SQL_SCRIPT = REPLACE(@SQL_SCRIPT, '{DB2Name}', @DB2_Name)

EXECUTE (@SQL_SCRIPT)


