--DONE


DECLARE @query NVARCHAR(MAX)
DECLARE @SQL_SCRIPT NVARCHAR(MAX)
DECLARE @DB1_Name NVARCHAR(50)
DECLARE @DB2_Name NVARCHAR(50)


SET @DB1_Name = '[LEADRS_CORE_DEV_DUI]';
SET @DB2_Name = '[LEADRS_TX_STAGING]';


SET @query = '
SET IDENTITY_INSERT {DB1Name}.dre.DRE_CASE_PAGES ON

insert into {DB1Name}.dre.DRE_CASE_PAGES
(	[DreCasePageId],
	[PageName],
	[Url],
	[PageOrder]
)
select [DRE_CASE_PAGE_ID],
	[PAGE_NAME],
	[ACTUAL_PAGE],
	[PAGE_ORDER]
from {DB2Name}.dbo.TBL_DRE_CASE_PAGES
WHERE [DRE_CASE_PAGE_ID] NOT IN (
    SELECT [DreCasePageId]
    FROM {DB1Name}.dre.DRE_CASE_PAGES
)

SET IDENTITY_INSERT {DB1Name}.dre.DRE_CASE_PAGES OFF';


SET @SQL_SCRIPT = REPLACE(@query, '{DB1Name}', @DB1_Name)
SET @SQL_SCRIPT = REPLACE(@SQL_SCRIPT, '{DB2Name}', @DB2_Name)


EXECUTE (@SQL_SCRIPT)


