--DONE


DECLARE @query NVARCHAR(MAX)
DECLARE @SQL_SCRIPT NVARCHAR(MAX)
DECLARE @DB1_Name NVARCHAR(50)
DECLARE @DB2_Name NVARCHAR(50)


SET @DB1_Name = '[LEADRS_CORE_DEV_DUI]';
SET @DB2_Name = '[LEADRS_TX_STAGING]';


SET @query = '
set IDENTITY_INSERT {DB1Name}.dre.DRE_CASE_NOTE_TYPES ON

insert into {DB1Name}.dre.DRE_CASE_NOTE_TYPES
(
	[DreCaseNoteTypeId],
	[DreCasePageId],
	[Section],
	[Active]
)
select [DRE_NOTE_TYPE_ID],
	TBL_DRE_CASE_NOTE_TYPES.[DRE_CASE_PAGE_ID],
	[SECTION],
	[ACTIVE]
from {DB2Name}.dbo.TBL_DRE_CASE_NOTE_TYPES
WHERE [DRE_NOTE_TYPE_ID] NOT IN (
    SELECT [DreCaseNoteTypeId]
    FROM {DB1Name}.dre.DRE_CASE_NOTE_TYPES
)

set IDENTITY_INSERT {DB1Name}.dre.DRE_CASE_NOTE_TYPES OFF';


SET @SQL_SCRIPT = REPLACE(@query, '{DB1Name}', @DB1_Name)
SET @SQL_SCRIPT = REPLACE(@SQL_SCRIPT, '{DB2Name}', @DB2_Name)


EXECUTE (@SQL_SCRIPT)


