--DONE

DECLARE @query NVARCHAR(MAX)
DECLARE @SQL_SCRIPT NVARCHAR(MAX)
DECLARE @DB1_Name NVARCHAR(50)
DECLARE @DB2_Name NVARCHAR(50)


SET @DB1_Name = '[LEADRS_CORE_DEV_DUI]';
SET @DB2_Name = '[LEADRS_TX_STAGING]';

--Foreign Key Check Will be changed.

SET @query = '
set IDENTITY_INSERT {DB1Name}.dre.DRE_CASES_OTHER_OFFICER ON

Alter Table {DB1Name}.dre.DRE_CASES_OTHER_OFFICER
NOCHECK CONSTRAINT [FK_DRE_CASES_OTHER_OFFICER_DRE_CASES_DreCaseId]
Alter Table {DB1Name}.dre.DRE_CASES_OTHER_OFFICER
NOCHECK CONSTRAINT [FK_DRE_CASES_OTHER_OFFICER_TBL_OPT_DRE_ROLES_DreRoleId]

insert into {DB1Name}.dre.DRE_CASES_OTHER_OFFICER
(	[OtherOfficerId],
	[DreCaseId],
	[DreRoleId],
	[OfficerAgency],
	[OfficerDeptId],
	[DreNumber],
	[OfficerId],
	[OfficerName],
	[PBT],
	[RollingLogNumber],
	[OfficerUserId],
	[Accepted],
	[IsOwner]
)
select [DRE_CASE_OTHER_OFFICER_ID],
	[DRE_CASE_ID],
	[DRE_ROLE_ID],
	[OFF_AGENCY],
	[OFF_DEPT_ID],
	[OFF_DRE],
	[OFF_ID],
	[OFF_NAME],
	COALESCE(CAST([PBT] AS int), 0),
	[ROLLING_LOG_NUMBER],
	CAST([USER_ID] as nvarchar(max)),
	0,0
from {DB2Name}.dbo.TBL_DRE_CASE_OTHER_OFFICER order by DRE_CASE_OTHER_OFFICER_ID
Alter Table {DB1Name}.dre.DRE_CASES_OTHER_OFFICER
CHECK CONSTRAINT [FK_DRE_CASES_OTHER_OFFICER_DRE_CASES_DreCaseId]
Alter Table {DB1Name}.dre.DRE_CASES_OTHER_OFFICER
CHECK CONSTRAINT [FK_DRE_CASES_OTHER_OFFICER_TBL_OPT_DRE_ROLES_DreRoleId]

set IDENTITY_INSERT {DB1Name}.dre.DRE_CASES_OTHER_OFFICER OFF';



SET @SQL_SCRIPT = REPLACE(@query, '{DB1Name}', @DB1_Name)
SET @SQL_SCRIPT = REPLACE(@SQL_SCRIPT, '{DB2Name}', @DB2_Name)

EXECUTE (@SQL_SCRIPT)


