--DONE

DECLARE @query NVARCHAR(MAX)
DECLARE @SQL_SCRIPT NVARCHAR(MAX)
DECLARE @DB1_Name NVARCHAR(50)
DECLARE @DB2_Name NVARCHAR(50)


SET @DB1_Name = '[LEADRS_CORE_DEV_DUI]';
SET @DB2_Name = '[LEADRS_TX_STAGING]';

--Foreign Key Check Will be changed.

SET @query = '
set IDENTITY_INSERT {DB1Name}.dre.DRE_CASE_NOTE_TYPES ON

Alter Table {DB1Name}.dre.DRE_CASE_NOTE_TYPES
NOCHECK CONSTRAINT FK_DRE_CASE_NOTE_TYPES_DRE_CASE_PAGES_DreCasePageId

insert into {DB1Name}.dre.DRE_CASE_NOTE_TYPES
(
	[DreCaseNoteTypeId],
	[DreCasePageId],
	[Section],
	[Active]
)
select [DRE_NOTE_TYPE_ID],
	[DRE_CASE_PAGE_ID],
	[SECTION],
	[ACTIVE]
from {DB2Name}.dbo.TBL_DRE_CASE_NOTE_TYPES

Alter Table {DB1Name}.dre.DRE_CASE_NOTE_TYPES
CHECK CONSTRAINT FK_DRE_CASE_NOTE_TYPES_DRE_CASE_PAGES_DreCasePageId
set IDENTITY_INSERT {DB1Name}.dre.DRE_CASE_NOTE_TYPES OFF';


SET @SQL_SCRIPT = REPLACE(@query, '{DB1Name}', @DB1_Name)
SET @SQL_SCRIPT = REPLACE(@SQL_SCRIPT, '{DB2Name}', @DB2_Name)


EXECUTE (@SQL_SCRIPT)


