--DONE

DECLARE @query NVARCHAR(MAX)
DECLARE @SQL_SCRIPT NVARCHAR(MAX)
DECLARE @DB1_Name NVARCHAR(50)
DECLARE @DB2_Name NVARCHAR(50)


SET @DB1_Name = '[LEADRS_CORE_DEV_DUI]';
SET @DB2_Name = '[LEADRS_TX_STAGING]';

--Foreign Key Check Will be changed.

SET @query = '
set IDENTITY_INSERT {DB1Name}.dre.DRE_CASE_TOXICOLOGY_DRUG ON

Alter Table {DB1Name}.dre.DRE_CASE_TOXICOLOGY_DRUG
NOCHECK CONSTRAINT [FK_DRE_CASE_TOXICOLOGY_DRUG_DRE_CASES_DreCaseId]
Alter Table {DB1Name}.dre.DRE_CASE_TOXICOLOGY_DRUG
NOCHECK CONSTRAINT [FK_DRE_CASE_TOXICOLOGY_DRUG_DreCaseToxSpec_DreCaseToxSpecId]
insert into {DB1Name}.dre.DRE_CASE_TOXICOLOGY_DRUG
(	[DreCaseToxDrugId],
	[DreCaseId],
	[DreCaseToxSpecId],
	[DpsDrugListId],
	[DrugResult],
	[DrugMeasurement]
)
select [TBL_DRE_CASE_TOXICOLOGY_DRUG_ID],
	[DRE_CASE_ID],
	[CASE_TOX_SPEC_ID],
	[DPS_DRUG_LIST_ID],
	[DRUG_RESULT],
	[DRUG_MEASUREMENT]
from {DB2Name}.dbo.TBL_DRE_CASE_TOXICOLOGY_DRUG
Alter Table {DB1Name}.dre.DRE_CASE_TOXICOLOGY_DRUG
CHECK CONSTRAINT [FK_DRE_CASE_TOXICOLOGY_DRUG_DRE_CASES_DreCaseId]
Alter Table {DB1Name}.dre.DRE_CASE_TOXICOLOGY_DRUG
CHECK CONSTRAINT [FK_DRE_CASE_TOXICOLOGY_DRUG_DreCaseToxSpec_DreCaseToxSpecId]
set IDENTITY_INSERT {DB1Name}.dre.DRE_CASE_TOXICOLOGY_DRUG OFF';


SET @SQL_SCRIPT = REPLACE(@query, '{DB1Name}', @DB1_Name)
SET @SQL_SCRIPT = REPLACE(@SQL_SCRIPT, '{DB2Name}', @DB2_Name)

EXECUTE (@SQL_SCRIPT)

