--DONE

DECLARE @query NVARCHAR(MAX)
DECLARE @SQL_SCRIPT NVARCHAR(MAX)
DECLARE @DB1_Name NVARCHAR(50)
DECLARE @DB2_Name NVARCHAR(50)


SET @DB1_Name = '[LEADRS_CORE_DEV_DUI]';
SET @DB2_Name = '[LEADRS_TX_STAGING]';


SET @query = '
Alter Table {DB1Name}.dre.DRE_CASES_VITAL_SIGNS
NOCHECK CONSTRAINT [FK_DRE_CASES_VITAL_SIGNS_DRE_CASES_DreCaseId]
insert into {DB1Name}.dre.DRE_CASES_VITAL_SIGNS
(	DreCaseId,
	BPDiastolic,
	BPSystolic,
	Temperature
)
select DRE_CASE_ID,
	BP_DIASTOLIC,
	BP_SYSTOLIC,
	TEMPERATURE
from {DB2Name}.dbo.TBL_DRE_CASE
Alter Table {DB1Name}.dre.DRE_CASES_VITAL_SIGNS
CHECK CONSTRAINT [FK_DRE_CASES_VITAL_SIGNS_DRE_CASES_DreCaseId]';



SET @SQL_SCRIPT = REPLACE(@query, '{DB1Name}', @DB1_Name)
SET @SQL_SCRIPT = REPLACE(@SQL_SCRIPT, '{DB2Name}', @DB2_Name)

EXECUTE (@SQL_SCRIPT)


