--DONE


DECLARE @query NVARCHAR(MAX)
DECLARE @SQL_SCRIPT NVARCHAR(MAX)
DECLARE @DB1_Name NVARCHAR(50)
DECLARE @DB2_Name NVARCHAR(50)


SET @DB1_Name = '[LEADRS_CORE_DEV_DUI]';
SET @DB2_Name = '[LEADRS_TX_STAGING]';


SET @query = '
SET IDENTITY_INSERT {DB1Name}.dre.TBL_OPT_DRE_NOTIFIED ON

insert into {DB1Name}.dre.TBL_OPT_DRE_NOTIFIED
(	[DreNotifiedId],
	[Description],
	[Active]
)
select [DRE_NOTIFIED_ID],
	[DRE_NOTIFIED_DESC],
	[ACTIVE]
from {DB2Name}.dbo.TBL_OPT_DRE_NOTIFIED
WHERE [DRE_NOTIFIED_ID] NOT IN (
    SELECT [DreNotifiedId]
    FROM {DB1Name}.dre.TBL_OPT_DRE_NOTIFIED
)
SET IDENTITY_INSERT {DB1Name}.dre.TBL_OPT_DRE_NOTIFIED ON';



SET @SQL_SCRIPT = REPLACE(@query, '{DB1Name}', @DB1_Name)
SET @SQL_SCRIPT = REPLACE(@SQL_SCRIPT, '{DB2Name}', @DB2_Name)

EXECUTE (@SQL_SCRIPT)


