--DONE


DECLARE @query NVARCHAR(MAX)
DECLARE @SQL_SCRIPT NVARCHAR(MAX)
DECLARE @DB1_Name NVARCHAR(50)
DECLARE @DB2_Name NVARCHAR(50)


SET @DB1_Name = '[LEADRS_CORE_DEV_DUI]';
SET @DB2_Name = '[LEADRS_TX_STAGING]';


SET @query = '
SET IDENTITY_INSERT {DB1Name}.dre.TBL_OPT_DRE_TYPES ON

insert into {DB1Name}.dre.TBL_OPT_DRE_TYPES
(	[DRETypeId],
	[TypeName],
	[Description],
	[Active])
select [DRE_TYPE_ID],
	[DRE_TYPE],
	[DRE_DESC],
	[ACTIVE]
from {DB2Name}.dbo.TBL_OPT_DRE_TYPE
WHERE [DRE_TYPE_ID] NOT IN (
    SELECT [DRETypeId]
    FROM {DB1Name}.dre.TBL_OPT_DRE_TYPES
)
SET IDENTITY_INSERT {DB1Name}.dre.TBL_OPT_DRE_TYPES OFF ';



SET @SQL_SCRIPT = REPLACE(@query, '{DB1Name}', @DB1_Name)
SET @SQL_SCRIPT = REPLACE(@SQL_SCRIPT, '{DB2Name}', @DB2_Name)

EXECUTE (@SQL_SCRIPT)


