--DONE


DECLARE @query NVARCHAR(MAX)
DECLARE @SQL_SCRIPT NVARCHAR(MAX)
DECLARE @DB1_Name NVARCHAR(50)
DECLARE @DB2_Name NVARCHAR(50)


SET @DB1_Name = '[LEADRS_CORE_DEV_DUI]';
SET @DB2_Name = '[LEADRS_TX_STAGING]';


SET @query = '
set IDENTITY_INSERT {DB1Name}.dre.DRE_CASE_NOTES ON

insert into {DB1Name}.dre.DRE_CASE_NOTES
(
	DreCaseNoteId,
	DreCaseId,
	DreCaseNoteTypeId,
	Notes
)
select DRE_CASE_NOTE_ID,
	TBL_DRE_CASE_NOTES.[DRE_CASE_ID],
	[DRE_NOTE_TYPE_ID],
	[NOTES]
from {DB2Name}.dbo.TBL_DRE_CASE_NOTES
	,{DB2Name}.dbo.TBL_DRE_CASE
WHERE TBL_DRE_CASE.DRE_CASE_ID = TBL_DRE_CASE_NOTES.DRE_CASE_ID
	AND
	[DRE_CASE_NOTE_ID] NOT IN (
    SELECT [DreCaseNoteId]
    FROM {DB1Name}.dre.DRE_CASE_NOTES
	WHERE DRE_CASE_NOTES.DreCaseId = TBL_DRE_CASE.DRE_CASE_ID
)
set IDENTITY_INSERT {DB1Name}.dre.DRE_CASE_NOTES OFF';


SET @SQL_SCRIPT = REPLACE(@query, '{DB1Name}', @DB1_Name)
SET @SQL_SCRIPT = REPLACE(@SQL_SCRIPT, '{DB2Name}', @DB2_Name)


EXECUTE (@SQL_SCRIPT)


