--DONE


DECLARE @query NVARCHAR(MAX)
DECLARE @SQL_SCRIPT NVARCHAR(MAX)
DECLARE @DB1_Name NVARCHAR(50)
DECLARE @DB2_Name NVARCHAR(50)


SET @DB1_Name = '[LEADRS_CORE_DEV_DUI]';
SET @DB2_Name = '[LEADRS_TX_STAGING]';


SET @query = '
set IDENTITY_INSERT {DB1Name}.dre.DRE_CASE_PIC ON

insert into {DB1Name}.dre.DRE_CASE_PIC
(	DreCasePictureId,
	[DreCaseId],
	[Section],
	[Sequence],
	[ImageData]
)
select DRE_CASE_PIC_ID,
	TBL_DRE_CASE_PIC.[DRE_CASE_ID],
	[SECTION],
	[SEQUENCE],
	[IMAGE_DATA]
from {DB2Name}.dbo.TBL_DRE_CASE_PIC
	,{DB2Name}.dbo.TBL_DRE_CASE
WHERE TBL_DRE_CASE_PIC.DRE_CASE_ID = TBL_DRE_CASE.DRE_CASE_ID
	AND [DRE_CASE_PIC_ID] NOT IN (
    SELECT [DreCasePictureId]
    FROM {DB1Name}.dre.DRE_CASE_PIC
	WHERE DRE_CASE_PIC.DreCaseId = TBL_DRE_CASE.DRE_CASE_ID
)
set IDENTITY_INSERT {DB1Name}.dre.DRE_CASE_PIC OFF';


SET @SQL_SCRIPT = REPLACE(@query, '{DB1Name}', @DB1_Name)
SET @SQL_SCRIPT = REPLACE(@SQL_SCRIPT, '{DB2Name}', @DB2_Name)

EXECUTE (@SQL_SCRIPT)


