--DONE


DECLARE @query NVARCHAR(MAX)
DECLARE @SQL_SCRIPT NVARCHAR(MAX)
DECLARE @DB1_Name NVARCHAR(50)
DECLARE @DB2_Name NVARCHAR(50)


SET @DB1_Name = '[LEADRS_CORE_DEV_DUI]';
SET @DB2_Name = '[LEADRS_TX_STAGING]';


SET @query = '

INSERT INTO {DB1Name}.dre.DRE_CASES_VITAL_SIGNS
(	DreCaseId,
	BPDiastolic,
	BPSystolic,
	Temperature
)
SELECT DRE_CASE_ID,
	BP_DIASTOLIC,
	BP_SYSTOLIC,
	TEMPERATURE
FROM {DB2Name}.dbo.TBL_DRE_CASE
WHERE [DRE_CASE_ID] NOT IN (
    SELECT [DreCaseId]
    FROM {DB1Name}.dre.DRE_CASES_VITAL_SIGNS
	WHERE DRE_CASES_VITAL_SIGNS.DreCaseId = TBL_DRE_CASE.DRE_CASE_ID
) ';



SET @SQL_SCRIPT = REPLACE(@query, '{DB1Name}', @DB1_Name)
SET @SQL_SCRIPT = REPLACE(@SQL_SCRIPT, '{DB2Name}', @DB2_Name)

EXECUTE (@SQL_SCRIPT)


