DECLARE @query NVARCHAR(MAX)
DECLARE @SQL_SCRIPT NVARCHAR(MAX)
DECLARE @DB1_Name NVARCHAR(50)
DECLARE @DB2_Name NVARCHAR(50)


SET @DB1_Name = '[LEADRS_CORE_DEV_DUI]';
SET @DB2_Name = '[LEADRS_TX_STAGING]';


SET @query = '
insert into {DB1Name}.dre.TBL_OPT_DPS_DRUG_LIST
(	[DpsDrug],
	[Active],
	[DpsDrugCategory]
)
select [DPS_DRUG],
	[ACTIVE],
	[DPS_DRUG_CATEGORY]
from {DB2Name}.dbo.TBL_OPT_DPS_DRUG_LIST';



SET @SQL_SCRIPT = REPLACE(@query, '{DB1Name}', @DB1_Name)
SET @SQL_SCRIPT = REPLACE(@SQL_SCRIPT, '{DB2Name}', @DB2_Name)

EXECUTE (@SQL_SCRIPT)


